### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by kamov** [fengyuanchen/uploader#2]
Hi,
what you mean that browser support is "latest 2" of chrome, Opera, safari and firefox?
Do you mean "almost version 2" ? or last 2 version?
Thanks!

**Comment by kamov** [comment]
There is a fallback when browser is not supported?

**Comment by fengyuanchen** [comment]
latest 2 = latest version and the previous version of current version.

**Comment by fengyuanchen** [comment]
Fallbacks:
1. HTML 5 upload (FormData)
2. Iframe upload

**Comment by kamov** [comment]
thanks
