### ISSUE TITLE
Manually upload

### ISSUE THREAD

**Issue by kamov** [fengyuanchen/uploader#3]
Hi,
I set autoUpload: false,
but now how to make file upload on submit of form?
I have a form with other input which are send via ajax.
Thanks

**Comment by kamov** [comment]
I would like to show preview of added file, and a way to remove them, then when user click "Submit" the form is send via ajax and also files.

**Comment by kamov** [comment]
I was able to trigger upload on click on submit.

However, I would like to show image preview before upload.

There is a way?

Thanks

**Comment by fengyuanchen** [comment]
http://fengyuanchen.github.io/uploader/advanced-example.html
