### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by kamov** [fengyuanchen/uploader#4]
Hi,
the upload progress seem not work, with large file that I tested, the upload progress is not moving, and only at the end.
There is a way to show a real progress, maybe by sending from server a notice about progress?
Thanks

**Comment by fengyuanchen** [comment]
http://fengyuanchen.github.io/uploader/advanced-example.html

**Comment by kamov** [comment]
Yes I see that. But if you try to upload very large file, the upload progress is show only at the end

**Comment by fengyuanchen** [comment]
The progress event are emulated in old browser which not support XMLHttpRequest Progress event. So if may not work as actual behavior.
